In [3]:
pip install qiskit

In [4]:
import numpy as np
from qiskit.quantum_info import Statevector, Operator

In [5]:
# 1. Tensor Product of Two Vectors

def tensor_product(vec1, vec2):
    return np.kron(vec1, vec2)

# Example vectors
psi = np.array([1, 0])  # |0⟩
phi = np.array([1/np.sqrt(2), 1/np.sqrt(2)])  # |+⟩

# Calculate the tensor product
result = tensor_product(psi, phi)
print("Tensor Product |ψ⟩ ⊗ |ϕ⟩:")
print(result)


Tensor Product |ψ⟩ ⊗ |ϕ⟩:
[0.70710678 0.70710678 0.         0.        ]


In [6]:
# 2. Create an Operator and Execute on State Vector

# Define a simple operator (e.g., Pauli-X operator)
X_operator = np.array([[0, 1],
                       [1, 0]])

# Execute the operator on the state vector |ψ⟩
new_state = X_operator @ psi
print("\nNew State after applying X operator on |0⟩:")
print(new_state)


New State after applying X operator on |0⟩:
[0 1]


In [7]:
# 3. Partial Measurement

def partial_measure(state, index):
    # For simplicity, we consider only measurement of a single qubit
    if index == 0:  # Measure the first qubit
        return np.array([state[0], state[2]]), np.array([state[1], state[3]])
    else:  # Measure the second qubit
        return np.array([state[0], state[1]]), np.array([state[2], state[3]])

# Get the measurement results
measured_0, measured_1 = partial_measure(result, 0)
print("\nPartial Measurement Results (Measurement on first qubit):")
print("Measured |0⟩ state:", measured_0)
print("Measured |1⟩ state:", measured_1)


Partial Measurement Results (Measurement on first qubit):
Measured |0⟩ state: [0.70710678 0.        ]
Measured |1⟩ state: [0.70710678 0.        ]


In [8]:
# 4. CSWAP and Toffoli Gates

# CSWAP Gate
CSWAP = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                  [0, 1, 0, 0, 0, 0, 0, 0],
                  [0, 0, 1, 0, 0, 0, 0, 0],
                  [0, 0, 0, 1, 0, 0, 0, 0],
                  [0, 0, 0, 0, 0, 1, 0, 0],
                  [0, 0, 0, 0, 1, 0, 0, 0],
                  [0, 0, 0, 0, 0, 0, 0, 1],
                  [0, 0, 0, 0, 0, 0, 1, 0]])

print("\nCSWAP Matrix Representation:")
print(CSWAP)


CSWAP Matrix Representation:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]


In [9]:
# Toffoli Gate
Toffoli = np.array([[1, 0, 0, 0, 0, 0, 0, 0],
                    [0, 1, 0, 0, 0, 0, 0, 0],
                    [0, 0, 1, 0, 0, 0, 0, 0],
                    [0, 0, 0, 1, 0, 0, 0, 0],
                    [0, 0, 0, 0, 1, 0, 0, 0],
                    [0, 0, 0, 0, 0, 1, 0, 0],
                    [0, 0, 0, 0, 0, 0, 0, 1],
                    [0, 0, 0, 0, 0, 0, 1, 0]])

print("\nToffoli Matrix Representation:")
print(Toffoli)


Toffoli Matrix Representation:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]]


We define the function tensor_product using NumPy's kron function to compute the tensor product of two vectors. Operator Application:

We define a simple Pauli-X operator and apply it to the |0⟩ state vector using matrix multiplication. Partial Measurement:

The partial_measure function simulates measuring one of the qubits in the composite state. Gate Representations:

The CSWAP and Toffoli gates are defined as 8x8 matrices to represent their action on 3 qubits.